import { test, expect } from '@playwright/test';
import { installApiMocks, setLocalAuthState } from './fixtures/api-mocks';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Reusable fixture path — the minimal WAV already generated by upload.spec.ts
const TEST_AUDIO_PATH = path.join(__dirname, 'fixtures', 'test-audio.wav');

/**
 * Ensure a minimal (but valid) WAV fixture exists before running tests.
 */
function ensureTestAudio() {
  if (!fs.existsSync(TEST_AUDIO_PATH)) {
    const header = Buffer.alloc(44);
    header.write('RIFF', 0);
    header.writeUInt32LE(36, 4);
    header.write('WAVE', 8);
    header.write('fmt ', 12);
    header.writeUInt32LE(16, 16);
    header.writeUInt16LE(1, 20);  // PCM
    header.writeUInt16LE(1, 22);  // mono
    header.writeUInt32LE(44100, 24); // sample rate
    header.writeUInt32LE(88200, 28); // byte rate
    header.writeUInt16LE(2, 32);   // block align
    header.writeUInt16LE(16, 34);  // bits per sample
    header.write('data', 36);
    header.writeUInt32LE(0, 40);
    fs.writeFileSync(TEST_AUDIO_PATH, header);
  }
}

/**
 * Intercept the upload endpoint to return a 409 Conflict.
 * MUST be registered AFTER installApiMocks — Playwright uses LIFO routing,
 * so the last-registered handler for a given URL pattern wins.
 */
async function overrideUploadAsDuplicate(page: Parameters<typeof installApiMocks>[0]) {
  await page.route('**/api/v1/transcription/upload', (route) => {
    const url = new URL(route.request().url());
    const force = url.searchParams.get('force');

    if (force === 'true') {
      // Force upload succeeds
      return route.fulfill({
        status: 200,
        json: {
          id: '99',
          title: 'test-audio-copy',
          status: 'uploaded',
          audio_path: '/data/uploads/test-audio-copy.wav',
          created_at: new Date().toISOString(),
        },
      });
    }

    // Without force — duplicate
    return route.fulfill({
      status: 409,
      json: {
        error: 'duplicate',
        existing_id: '1',
        existing_title: 'Team Standup March 10',
      },
    });
  });
}

/**
 * Trigger the hidden audio file input so the app processes the upload.
 */
async function triggerFileUpload(page: Parameters<typeof installApiMocks>[0]) {
  const fileInput = page.locator('input[type="file"][accept*="audio"]').first();
  await fileInput.setInputFiles(TEST_AUDIO_PATH);
}

// ---------------------------------------------------------------------------

test.beforeEach(async ({ page }) => {
  ensureTestAudio();
  await setLocalAuthState(page);
  // Install base mocks first; individual tests may override specific routes afterwards
  await installApiMocks(page);
});

test.describe('Duplicate Upload Detection', () => {
  // ── 1. Normal upload succeeds (baseline) ──────────────────────────────────
  test('first upload succeeds without showing a duplicate dialog', async ({ page }) => {
    // The default installApiMocks already returns 200 for upload — no override needed.
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    // Confirm the upload request is intercepted by the mock
    const uploadRequest = page.waitForRequest('**/api/v1/transcription/upload');

    await triggerFileUpload(page);

    const req = await uploadRequest;
    expect(req.method()).toBe('POST');

    // Wait briefly then assert the duplicate dialog has NOT appeared
    await page.waitForTimeout(500);
    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).not.toBeVisible();
  });

  // ── 2. Duplicate upload triggers the AlertDialog ──────────────────────────
  test('duplicate upload shows "Duplicate File" AlertDialog', async ({ page }) => {
    // Override the upload route to return 409 AFTER base mocks are installed
    await overrideUploadAsDuplicate(page);

    await page.goto('/');
    await page.waitForLoadState('networkidle');

    await triggerFileUpload(page);

    // Dialog should appear
    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });

    // Title and description
    await expect(dialog.locator('text=Duplicate File')).toBeVisible();
    await expect(dialog).toContainText('Team Standup March 10');

    // All three action buttons must be present
    await expect(dialog.locator('button:has-text("Cancel")')).toBeVisible();
    await expect(dialog.locator('button:has-text("Open Existing")')).toBeVisible();
    await expect(dialog.locator('button:has-text("Upload Anyway")')).toBeVisible();
  });

  // ── 3. Cancel dismisses the dialog ───────────────────────────────────────
  test('clicking Cancel closes the dialog without force-uploading', async ({ page }) => {
    let forceUploadCalled = false;

    await overrideUploadAsDuplicate(page);

    // Spy on any subsequent force upload attempts
    await page.route('**/api/v1/transcription/upload', (route) => {
      const url = new URL(route.request().url());
      if (url.searchParams.get('force') === 'true') {
        forceUploadCalled = true;
        return route.fulfill({
          status: 200,
          json: { id: '99', title: 'copy', status: 'uploaded', audio_path: '', created_at: '' },
        });
      }
      return route.fulfill({
        status: 409,
        json: { error: 'duplicate', existing_id: '1', existing_title: 'Team Standup March 10' },
      });
    });

    await page.goto('/');
    await page.waitForLoadState('networkidle');

    await triggerFileUpload(page);

    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });

    await dialog.locator('button:has-text("Cancel")').click();

    // Dialog should close
    await expect(dialog).not.toBeVisible({ timeout: 3000 });

    // No force upload should have been attempted
    await page.waitForTimeout(300);
    expect(forceUploadCalled).toBe(false);
  });

  // ── 4. "Open Existing" navigates to /audio/{id} ──────────────────────────
  test('clicking "Open Existing" navigates to the existing transcription', async ({ page }) => {
    await overrideUploadAsDuplicate(page);

    await page.goto('/');
    await page.waitForLoadState('networkidle');

    await triggerFileUpload(page);

    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });

    await dialog.locator('button:has-text("Open Existing")').click();

    // Dialog should close
    await expect(dialog).not.toBeVisible({ timeout: 3000 });

    // Should have navigated to /audio/1 (existing_id from mock)
    await expect(page).toHaveURL(/\/audio\/1/, { timeout: 5000 });
  });

  // ── 5. "Upload Anyway" re-uploads with force=true ────────────────────────
  test('clicking "Upload Anyway" re-uploads with force=true', async ({ page }) => {
    // Override upload: non-force → 409, force → 200.
    // This handler is registered after beforeEach's installApiMocks, so it takes
    // LIFO priority and intercepts ALL upload requests for this test.
    await page.route('**/api/v1/transcription/upload', (route) => {
      const url = new URL(route.request().url());

      if (url.searchParams.get('force') === 'true') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 99,
            title: 'test-audio-copy',
            status: 'uploaded',
            audio_path: '/data/uploads/test-audio-copy.wav',
            created_at: new Date().toISOString(),
          }),
        });
      }

      // Non-force request → duplicate
      return route.fulfill({
        status: 409,
        contentType: 'application/json',
        body: JSON.stringify({
          error: 'duplicate',
          existing_id: '1',
          existing_title: 'Team Standup March 10',
        }),
      });
    });

    await page.goto('/');
    await page.waitForLoadState('networkidle');

    await triggerFileUpload(page);

    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });

    // Set up a listener for the force upload request BEFORE clicking
    const forceUploadResponse = page.waitForResponse(
      (resp) => resp.url().includes('/api/v1/transcription/upload') && resp.url().includes('force=true'),
      { timeout: 5000 },
    );

    await dialog.locator('button:has-text("Upload Anyway")').click();

    // Dialog should close immediately
    await expect(dialog).not.toBeVisible({ timeout: 3000 });

    // Wait for the force upload response and verify it succeeded
    const resp = await forceUploadResponse;
    expect(resp.status()).toBe(200);
  });

  // ── 6. Dialog description shows the correct existing title ───────────────
  test('dialog description shows the correct existing file title', async ({ page }) => {
    // Override with a different existing title to verify dynamic rendering
    await page.route('**/api/v1/transcription/upload', (route) => {
      return route.fulfill({
        status: 409,
        json: {
          error: 'duplicate',
          existing_id: '2',
          existing_title: 'Product Review',
        },
      });
    });

    await page.goto('/');
    await page.waitForLoadState('networkidle');

    await triggerFileUpload(page);

    const dialog = page.locator('[role="alertdialog"]');
    await expect(dialog).toBeVisible({ timeout: 5000 });
    await expect(dialog).toContainText('Product Review');
  });
});
